# Generated by Django 5.0.4 on 2024-05-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tv',
            options={'verbose_name': 'телевизор', 'verbose_name_plural': 'телевизоры'},
        ),
    ]
